version: "3.9"
services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: onize/mipad-api
    command: python manage.py runserver 0.0.0.0:10008
    volumes:
      - ./app:/app
    ports:
      - "10008:10008"
    env_file:
      - ./.env
    restart: always
    
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    env_file:
      - ./.env

  celery:
    <<: *api
    command: celery -A core.celery worker --pool=threads --loglevel=info --logfile=logs/celery.log
    ports: []
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - api

  celery-beat:
    <<: *api
    command: celery -A core beat -l info
    ports: []
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - celery
