USER_PROFESSIONS = (
    ('DESIGN', 'DESIGN'),
    ('MEDICINE', 'MEDICINE'),
    ('PSYCHOLOGY', 'PSYCHOLOGY'),
    ('ENGINEERING', 'ENGINEERING'),
    ('GEOGRAPHY', 'GEOGRAPHY'),
    ('BOTANY', 'BOTANY'),
    ('ENVIRONMENTAL_SCIENCE', 'ENVIRONMENTAL_SCIENCE'),
    ('QUANTITY_SURVEYING', 'QUANTITY_SURVEYING'),
)


CITIES = (
    ('LAGOS_PORTUGAL', 'LAGOS_PORTUGAL'),
    ('LAGOS_NIGERIA', 'LAGOS_NIGERIA'),
    ('LAGOS_BRAZIL', 'LAGOS_BRAZIL')
)


TOKEN_TYPE = (
    ('ACCOUNT_VERIFICATION', 'ACCOUNT_VERIFICATION'),
    ('PASSWORD_RESET', 'PASSWORD_RESET')
)